config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope :panel do
    devise_for :users
    resources :pages, param: :id, path: '/' do
      resource :page_profile, only: %i[edit update]
      resource :page_appearance, only: %i[edit update]
      resource :page_contact, only: %i[edit update]
      resource :page_integration, only: %i[edit update]
      resources :content_items do
        member do
          patch 'reorder-link'
        end
      end
    end
  end

  get 'terms', to: 'public#terms', as: :public_terms
  get 'privacy', to: 'public#privacy', as: :public_privacy
  get 'p/thank-you', to: 'public#thank_you'
  match ':page_slug', to: 'public#page', as: :public_page, via: %i[get post]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'public#index'
end

app/models/page_profile.rb
class PageProfile < ApplicationRecord
  belongs_to :page

  has_one_attached :profile_image
  has_one_attached :header_image

  validates :profile_image, blob: { content_type: ['image/png', 'image/jpeg', 'image/gif'], size_range: 0..(1.megabytes) }
  validates :header_image, blob: { content_type: ['image/png', 'image/jpeg', 'image/gif'], size_range: 0..(1.megabytes) }
  validates_length_of :display_name, { maximum: 60 }
  validates_length_of :location, { maximum: 60 }
end

app/controllers/page_profiles_controller.rb
class PageProfilesController < ApplicationController
  before_action :set_page
  before_action :set_page_profile, only: %i[edit update]

  # GET /page/1/page_profiles/edit
  def edit
  end

  # PATCH/PUT /page/1/page_profiles/1
  def update
    if @page_profile.update(page_profile_params)
      redirect_to edit_page_page_profile_url(@page_profile.page), notice: 'Profile information successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_page_profile
    @page_profile = @page.page_profile
  end

  # Only allow a list of trusted parameters through.
  def page_profile_params
    params.require(:page_profile).permit(:display_name, :location, :description, :profile_image, :header_image)
  end
end

app/helpers/page_profiles_helper.rb
module PageProfilesHelper
end

app/views/page_profiles/_form.html.erb
<div class="container-md">
  <h2>Profile information</h2>

  <div class="card">
    <div class="card-body">
      <%= simple_form_for(@page_profile, url: page_page_profile_url) do |f| %>
        <div class="image-container mb-4">
          <div class="image-header">
            <% if @page_profile.header_image.representable? %>
              <%= image_tag @page_profile.header_image %>
            <% else %>
              <%= image_tag 'header_image_placeholder.svg' %>
            <% end %>
          </div>
          <div class="image-profile">
            <% if @page_profile.profile_image.representable? %>
              <%= image_tag @page_profile.profile_image, class: 'rounded-circle' %>
            <% else %>
              <%= image_tag 'profile_image_placeholder.svg', class: 'rounded-circle' %>
            <% end %>
          </div>
        </div>

        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :profile_image, input_html: { direct_upload: true, accept: 'image/jpeg, image/png, image/gif', size: '1048576', class: 'form-control' } %>
          <%= f.input :header_image, input_html: { direct_upload: true, accept: 'image/jpeg, image/png, image/gif', size: '1048576', class: 'form-control' } %>
          <%= f.input :display_name %>
          <%= f.input :location %>
          <%= f.input :description %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: 'btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/page_profiles/edit.html.erb
<%= render "form", page_profile: @page_profile %>