config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope :panel do
    devise_for :users
    resources :pages, param: :id, path: '/' do
      resource :page_profile, only: %i[edit update]
      resource :page_appearance, only: %i[edit update]
      resource :page_contact, only: %i[edit update]
      resource :page_integration, only: %i[edit update]
      resources :content_items do
        member do
          patch 'reorder-link'
        end
      end
    end
  end

  get 'terms', to: 'public#terms', as: :public_terms
  get 'privacy', to: 'public#privacy', as: :public_privacy
  get 'p/thank-you', to: 'public#thank_you'
  match ':page_slug', to: 'public#page', as: :public_page, via: %i[get post]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'public#index'
end

app/views/pages/_appearance_form.html.erb
<%= simple_form_for(page_appearance, url: update_appearance_page_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :theme, collection: Appearance::Constants::THEMES.keys, as: :radio_buttons %>
    <%= f.input :font, collection: Appearance::Constants::FONTS.keys, as: :radio_buttons %>
    <%= f.input :primary_color, as: :color %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary'%>
  </div>
<% end %>

app/views/pages/_contact_form.html.erb
<%= simple_form_for(page_contact, url: update_contact_page_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :display_public_email, as: :boolean %>
    <%= f.input :public_email %>
    <%= f.input :display_public_phone, as: :boolean %>
    <%= f.input :public_phone %>
    <%= f.input :public_phone_type, collection: PageContact.public_phone_types.keys, as: :radio_buttons %>
    <%#= f.input :main_contact_links %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary'%>
  </div>
<% end %>

app/views/pages/_form.html.erb
<div class="container-md">
  <h2>Page settings</h2>

  <div class="card">
    <div class="card-body">
      <%= simple_form_for(page) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :slug, label: 'Page URL', hint: 'Select your page URL' do %>
            <div class="input-group">
              <span class="input-group-text">https://page.digital/</span>
              <%= f.input_field :slug, class: 'form-control' %>
            </div>
          <% end %>
          <%= f.input :published, hint: 'You can deactivate your page whenever you want' %>
          <%= f.input :lock_code, hint: 'Ask for a secret code to enter to your page' %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: 'btn-primary'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_integration_form.html.erb
<%= simple_form_for(page_integration, url: update_integration_page_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :facebook_pixel %>
    <%= f.input :google_analytics %>
    <%= f.input :email_capture, as: :boolean %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary'%>
  </div>
<% end %>

app/views/pages/_profile_form.html.erb
<%= simple_form_for(page_profile, url: update_profile_page_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :display_name %>
    <%= f.input :location %>
    <%= f.input :description %>
    <%= f.input :profile_image, input_html: { direct_upload: true, accept: 'image/*' } %>
    <%= f.input :header_image, input_html: { direct_upload: true, accept: 'image/*' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary'%>
  </div>
<% end %>

app/views/pages/edit.html.erb
<%= render "form", page: @page %>

app/views/pages/new.html.erb
<%= render "form", page: @page %>