config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope :panel do
    devise_for :users
    resources :pages, param: :id, path: '/' do
      resource :page_profile, only: %i[edit update]
      resource :page_appearance, only: %i[edit update]
      resource :page_contact, only: %i[edit update]
      resource :page_integration, only: %i[edit update]
      resources :content_items do
        member do
          patch 'reorder-link'
        end
      end
    end
  end

  get 'terms', to: 'public#terms', as: :public_terms
  get 'privacy', to: 'public#privacy', as: :public_privacy
  get 'p/thank-you', to: 'public#thank_you'
  match ':page_slug', to: 'public#page', as: :public_page, via: %i[get post]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'public#index'
end

app/models/content_item.rb
class ContentItem < ApplicationRecord
  include Validators

  belongs_to :page

  has_one_attached :custom_thumbnail_image

  validates :custom_thumbnail_image, blob: { content_type: ['image/png', 'image/jpeg', 'image/gif'], size_range: 0..(1.megabytes) }
  validates :url, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :subtitle, length: { maximum: 255 }
  validates :position, numericality: { only_integer: true }, length: { maximum: 2 }

  after_create :update_position_in_list

  scope :ordered, -> { order(position: :asc) }
  scope :includes_all, -> { ordered.includes([:page, { custom_thumbnail_image_attachment: :blob }]) }

  # on position change update the entire list of content items
  def update_position(index)
    self.position = index
    return unless position_changed?

    update_position_in_list
  end

  private

  # update the entire list of content items
  def update_position_in_list
    ActiveRecord::Base.transaction do
      ids = ContentItem.select(:id).where(page_id:).ordered.collect(&:id)
      ids.delete(id)
      if position >= ids.length
        ids.push(id)
      else
        ids.insert(position, id)
      end
      values = ids.map.with_index { |_, index| { position: index } }
      ContentItem.update!(ids, values)
    end
  end
end

app/controllers/content_items_controller.rb
class ContentItemsController < ApplicationController
  before_action :set_page
  before_action :set_content_item, only: %i[ show edit update destroy reorder_link ]

  # GET /content_items or /content_items.json
  def index
    @content_items = @page.content_items.includes_all
  end

  # GET /content_items/1 or /content_items/1.json
  def show
  end

  # GET /content_items/new
  def new
    @content_item = @page.content_items.new
  end

  # GET /content_items/1/edit
  def edit
  end

  # POST /content_items or /content_items.json
  def create
    @content_item = @page.content_items.new(content_item_params)

    respond_to do |format|
      if @content_item.save
        format.html { redirect_to page_content_item_url(@page, @content_item), notice: "Content item was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content_items/1
  def update
    respond_to do |format|
      if @content_item.update(content_item_params)
        format.html { redirect_to page_content_item_url(@page, @content_item), notice: "Content item was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_items/1
  def destroy
    @content_item.destroy

    respond_to do |format|
      format.html { redirect_to page_content_items_url, notice: "Content item was successfully destroyed." }
      format.turbo_stream
    end
  end

  # PATCH /content_items/reorderLink
  def reorder_link
    destination = params[:destination]
    respond_to do |format|
      if @content_item.update_position(destination)
        format.json { head :ok }
      else
        format.json { head :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_content_item
    @content_item = @page.content_items.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def content_item_params
    params.require(:content_item).permit(:url, :title, :subtitle, :embedded, :highlight, :custom_thumbnail, :custom_thumbnail_image, :schedule, :schedule_date)
  end
end

app/helpers/content_items_helper.rb
module ContentItemsHelper
end

app/views/content_items/_content_item.html.erb
<%= turbo_frame_tag content_item, class: 'page_content_item' do %>
  <div class="card card-hover">
    <div class="card-body">
      <div class="row">
        <div class="col-auto d-none d-md-block content-item-image">
          <%= link_to content_item_image_tag(content_item.custom_thumbnail_image, content_item.url, class: 'rounded', size: 75),
                      edit_page_content_item_path(content_item.page, content_item) %>
        </div>
        <div class="col content-item-info d-flex align-items-center overflow-hidden">
          <%= link_to edit_page_content_item_path(content_item.page, content_item), class: 'd-block text-decoration-none w-100' do %>
            <div class="item-title text-truncate" title="<%= content_item.title %>"><%= content_item.title %></div>
            <div class="item-url text-muted text-truncate" title="<%= content_item.url %>"><%= content_item.url %></div>
          <% end %>
        </div>
        <div class="col-auto content-item-move-icon d-flex align-items-center cursor-grab" data-reorder-href="<%= reorder_link_page_content_item_path(content_item.page, content_item) %>">
          <i class="bi bi-arrow-down-up"></i>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/content_items/_form.html.erb
<%= simple_form_for(@content_item, url: url_for([@content_item.page, @content_item])) do |f| %>
  <div class="card">
    <div class="card-body">
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :url %>
        <%= f.input :title %>
        <%= f.input :subtitle %>

        <div class="extra-features mt-4">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#<%= dom_id(@content_item, 'tab_highlight') %>" type="button" role="tab" aria-controls="profile" aria-selected="true">
                <%= f.input :highlight, label: false do %>
                  <%= f.input_field :highlight, class: 'form-check-input' %>
                  <span>Highlight</span>
                <% end %>
              </button>
            </li>
<!--            <li class="nav-item" role="presentation">-->
<!--              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#<%#= dom_id(@content_item, 'tab_embedded') %>" type="button" role="tab" aria-controls="home" aria-selected="true">-->
                <%#= f.input :embedded, label: false do %>
                  <%#= f.input_field :embedded, class: 'form-check-input', disabled: true %>
<!--                  <span>Embedded</span>-->
                <%# end %>
<!--              </button>-->
<!--            </li>-->
            <li class="nav-item" role="presentation">
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#<%= dom_id(@content_item, 'tab_custom_thumbnail') %>" type="button" role="tab" aria-controls="contact" aria-selected="false">
                <%= f.input :custom_thumbnail, label: false do %>
                  <%= f.input_field :custom_thumbnail, class: 'form-check-input' %>
                  <span>Custom thumbnail</span>
                <% end %>
              </button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#<%= dom_id(@content_item, 'tab_schedule') %>" type="button" role="tab" aria-controls="contact" aria-selected="false">
                <%= f.input :schedule, label: false do %>
                  <%= f.input_field :schedule, class: 'form-check-input' %>
                  <span>Schedule</span>
                <% end %>
              </button>
            </li>
          </ul>
          <div class="tab-content bg-light">
            <div class="tab-pane fade show active p-3" id="<%= dom_id(@content_item, 'tab_highlight') %>" role="tabpanel" aria-labelledby="highlight-tab">
              <h5>Highlight link</h5>
              <p>Draw attention to your most important link.</p>
            </div>
<!--            <div class="tab-pane fade p-3" id="<%#= dom_id(@content_item, 'tab_embedded') %>" role="tabpanel" aria-labelledby="embedded-tab">-->
<!--              <h5>Embedded link (Work in progress)</h5>-->
<!--              <p>Display the link content directly in your page, like a Youtube video or Instagram post when it's possible.</p>-->
<!--            </div>-->
            <div class="tab-pane fade p-3" id="<%= dom_id(@content_item, 'tab_custom_thumbnail') %>" role="tabpanel" aria-labelledby="custom_thumbnail-tab">
              <h5>Custom thumbnail</h5>
              <p>Add a Thumbnail image or Icon to this Link (recommended size: 150x150 px).</p>
              <div class="row">
                <div class="col-auto">
                  <% if @content_item.custom_thumbnail_image.representable? %>
                    <%= image_tag @content_item.custom_thumbnail_image, size: 100 %>
                  <% end %>
                </div>
                <div class="col d-flex align-items-center">
                  <%= f.input :custom_thumbnail_image, label: false, input_html: { direct_upload: true, accept: 'image/jpeg, image/png, image/gif', size: '1048576', class: 'form-control' } %>
                </div>
              </div>
            </div>
            <div class="tab-pane fade p-3" id="<%= dom_id(@content_item, 'tab_schedule') %>" role="tabpanel" aria-labelledby="schedule-tab">
              <h5>Schedule a link</h5>
              <p>Schedule when your Link go live.</p>
              <%= f.input :schedule_date, as: :date, html5: true %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <div class="d-flex flex-row-reverse justify-content-between">
        <div>
          <%= link_to 'Cancel', page_content_items_url(@content_item.page), class: 'btn' %>
          <%= f.button :submit, class: 'btn-primary' %>
        </div>
        <%= link_to 'Delete', [@content_item.page, @content_item], class: 'btn btn-danger', data: { turbo_method: :delete } if @content_item.persisted? %>
      </div>
    </div>
  </div>
<% end %>

app/views/content_items/create.turbo_stream.erb
<%= turbo_stream.prepend 'page_content_items', @content_item %>
<%= turbo_stream.update ContentItem.new, '' %>

app/views/content_items/destroy.turbo_stream.erb
<%= turbo_stream.remove @content_item %>

app/views/content_items/edit.html.erb
<%= link_to "Back links", page_content_items_path %>

<h1>Editing Link</h1>

<%= turbo_frame_tag @content_item do %>
  <%= render "form", content_item: @content_item %>
<% end %>

app/views/content_items/index.html.erb
<div class="container-md">
  <!--Content item actions-->
  <div class="actions row py-3">
    <div class="col-12 col-md d-grid">
      <%= link_to "New link 🔗", new_page_content_item_path, class: 'btn btn-primary', data: { turbo_frame: dom_id(ContentItem.new) } %>
    </div>
    <div class="col-md-1 py-2 my-md-0">
    </div>
    <div class="col-12 col-md d-grid">
      <%= render 'components/explore-ideas-modal' %>
    </div>
  </div>

  <!--New content item form-->
  <div class="my-4">
    <%= turbo_frame_tag ContentItem.new do %>
    <% end %>
  </div>

  <!--List of content items-->
  <%= turbo_frame_tag :page_content_items, class: 'd-flex flex-column gap-3' do %>
    <% @content_items.each do |content_item| %>
      <%= render content_item %>
    <% end %>
  <% end %>
</div>

app/views/content_items/new.html.erb
<%= link_to "Back links", page_content_items_path %>

<h1>New Link</h1>

<%= turbo_frame_tag @content_item do %>
  <%= render "form", content_item: @content_item %>
<% end %>

app/views/content_items/show.html.erb
<%= link_to "Back links", page_content_items_path %>

<h1>Displaying Link</h1>

<%= turbo_frame_tag @content_item do %>
  <%= render @content_item %>
<% end %>

<div>
  <%= link_to "Edit this content item", edit_page_content_item_path(@content_item) %>
  <%= button_to "Destroy this content item", page_content_items_path(@content_item), method: :delete %>
</div>