config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope :panel do
    devise_for :users
    resources :pages, param: :id, path: '/' do
      resource :page_profile, only: %i[edit update]
      resource :page_appearance, only: %i[edit update]
      resource :page_contact, only: %i[edit update]
      resource :page_integration, only: %i[edit update]
      resources :content_items do
        member do
          patch 'reorder-link'
        end
      end
    end
  end

  get 'terms', to: 'public#terms', as: :public_terms
  get 'privacy', to: 'public#privacy', as: :public_privacy
  get 'p/thank-you', to: 'public#thank_you'
  match ':page_slug', to: 'public#page', as: :public_page, via: %i[get post]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'public#index'
end

app/models/page_appearance.rb
class PageAppearance < ApplicationRecord
  belongs_to :page

  enum theme: Appearance::Constants::THEMES, _prefix: true
  enum font: Appearance::Constants::FONTS, _prefix: true
  enum primary_color: Appearance::Constants::COLORS, _prefix: true
end

app/controllers/page_appearances_controller.rb
class PageAppearancesController < ApplicationController
  before_action :set_page
  before_action :set_page_appearance, only: %i[edit update]

  # GET /page/1/page_appearances/edit
  def edit
  end

  # PATCH/PUT /page/1/page_appearances
  def update
    if @page_appearance.update(page_appearance_params)
      redirect_to edit_page_page_appearance_url(@page_appearance.page), notice: 'Appearance successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_page_appearance
    @page_appearance = @page.page_appearance
  end

  # Only allow a list of trusted parameters through.
  def page_appearance_params
    params.require(:page_appearance).permit(:theme, :font, :primary_color)
  end
end

app/helpers/page_appearances_helper.rb
module PageAppearancesHelper
end

app/views/page_appearances/_form.html.erb
<div class="container-md">
  <h2>Appearance</h2>

  <div class="card">
    <div class="card-body">
      <%= simple_form_for(@page_appearance, url: page_page_appearance_url) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :theme, collection: Appearance::Constants::THEMES.keys,as: :radio_buttons,
                      item_label_class: 'btn btn-outline-primary btn-lg bg-transparent text-body border border-2', collection_wrapper_tag: 'div',
                      collection_wrapper_class: 'row', item_wrapper_class: 'col col-6 col-md-4' %>
          <%= f.input :font, collection: Appearance::Constants::FONTS.keys, as: :radio_buttons,
                      item_label_class: 'btn btn-outline-primary btn-lg bg-transparent text-body border border-2', collection_wrapper_tag: 'div',
                      collection_wrapper_class: 'row', item_wrapper_class: 'col col-6 col-md-4' %>
          <div class="color-picker">
            <%= f.input :primary_color, collection: Appearance::Constants::COLORS.keys, as: :radio_buttons,
                        item_label_class: 'btn btn-primary btn-lg border border-2', collection_wrapper_tag: 'div',
                        collection_wrapper_class: 'row', item_wrapper_class: 'col col-6 col-md-3' %>
          </div>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: 'btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/page_appearances/edit.html.erb
<%= render "form", page_appearance: @page_appearance %>